spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/workflow?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  activiti:
    database-schema-update: true
    check-process-definitions: false

