server:
  port: 4444
spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        jdbc-url: jdbc:mysql://localhost:3306/tb_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
      ds1:
        jdbc-url: jdbc:mysql://localhost:3306/tb_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
    sharding:
      tables:
        certificate:
          table-strategy:
            inline:
              sharding-column: cert_id
              algorithm-expression: certificate_$->{cert_id % 10}
          key-generator:
            column: cert_id
            type: SNOWFLAKE
            props:
              worker:
                id: 123
          actual-data-nodes: ds0.certificate_$->{[0,1,2,3,4,5,6,7,8,9]}, ds1.certificate_$->{[0,1,2,3,4,5,6,7,8,9]}
      binding-tables: certificate
      default-database-strategy:
        inline:
          sharding-column: cert_id
          algorithm-expression: ds$->{cert_id % 2}
    props:
      sql:
        show: true # 打印 SQL
# mybatis 配置内容
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liangw.mapper
